[package]
name = "cydia_substrate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.153"
objc2 = "0.5.0"
substrate_sys = { path = "../substrate_sys/" }
